"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

const translations = {
  en: {
    brand_title: "Scheme",
    brand_accent: "Compass",
    brand_sub: "Your Guide to the Right Government Scheme",
    nav_home: "Home",
    nav_find_schemes: "Find Schemes",
    nav_how_it_works: "How It Works",
    nav_about: "About",
    nav_help: "Help & Support",
    gov_title: "Government of India",
    gov_ministry: "Ministry of Social Justice and Empowerment",
    hero_eyebrow: "SCHEME DISCOVERY PORTAL",
    hero_title_1: "Find the Right",
    hero_title_2: "Government Scheme",
    hero_title_3: "for You",
    hero_desc: "Discover financial and educational support schemes based on your needs, eligibility and goals — simply and clearly.",
    hero_btn: "Find a Scheme",
    need_heading: "What do you need help with?",
    need_sub: "Choose an option and we’ll guide you through the relevant government schemes.",
    need_biz_title: "Start a Business",
    need_biz_desc: "Explore financial support to start your business.",
    need_edu_title: "Education",
    need_edu_desc: "Find education loans and financial assistance.",
    need_growth_title: "Expand My Business",
    need_growth_desc: "Find support to grow and strengthen your business.",
    need_money_title: "Other Financial Need",
    need_money_desc: "Explore other financial assistance options.",
    explore: "Explore",
    trust_gov_title: "Trusted by Government",
    trust_gov_desc: "Official scheme information",
    trust_safe_title: "Safe & Secure",
    trust_safe_desc: "Your information matters",
    trust_partners_title: "100+ Channel Partners",
    trust_partners_desc: "Across financial networks",
    trust_coverage_title: "Pan India Coverage",
    trust_coverage_desc: "Support across India",
    step1_eyebrow: "STEP 1 OF 2",
    step1_title: "What are you looking for?",
    step1_sub: "Select your requirement to discover eligible government schemes.",
    continue: "Continue",
    form_title: "Business Assistance",
    form_sub: "Answer a few simple questions so we can identify relevant schemes.",
    project_type_label: "Project type / Business idea",
    project_type_ph: "e.g. Retail Shop, Manufacturing, Dairy Farm",
    project_cost_label: "Estimated project cost",
    project_cost_ph: "₹ Enter amount",
    family_income_label: "Annual family income",
    family_income_ph: "₹ Enter annual income",
    social_category_label: "Social category",
    social_category_sc: "Scheduled Caste (SC)",
    social_category_st: "Scheduled Tribe (ST)",
    social_category_obc: "Other Backward Class (OBC)",
    social_category_gen: "General / Other",
    state_label: "Applicant State",
    state_ph: "Enter your state (e.g. Tamil Nadu, Karnataka, Uttar Pradesh)",
    natural_input_label: "Or describe your need naturally in your language:",
    natural_input_ph: "e.g. I need a business loan of 5 lakhs to start a grocery store in Karnataka",
    find_matching_btn: "Find Matching Schemes",
    rec_evaluated: "CANDIDATES EVALUATED · CONVEX BACKEND & SARVAM NLU",
    rec_title: "Recommended Schemes",
    rec_sub: "Based on your criteria and natural language intent, here are the top evaluated scheme recommendations.",
    status_eligible: "ELIGIBLE",
    status_requires_verification: "REQUIRES VERIFICATION",
    status_ineligible: "INELIGIBLE",
    gov_sector: "Government Sector",
    channel_partner: "Channel Partner",
    max_benefit: "Maximum Benefit",
    match_confidence: "Match Confidence",
    reasons_label: "Evaluation Reasons",
    view_details: "View Scheme Details",
    no_matching: "No Matching Schemes Found",
    no_matching_sub: "Try adjusting your search criteria or purpose.",
    back_to_find: "Back to Find Scheme",
    scheme_details_title: "SCHEME DETAILS",
    eligibility_docs_title: "Eligibility & Documents Required",
    documents: "Documents Required",
    fin_support_title: "Financial Support & Benefit",
    estimate_emi: "Estimate EMI",
    find_nearby_partner: "Find Channel Partners",
    partners_title: "Eligible Channel Partners",
    partners_sub: "Discovered Physical Branches via Mappls Integration",
    use_current_location: "📍 Use Current Location",
    getting_location: "Detecting your location...",
    location_denied: "Location permission denied or unavailable. Enter location manually below.",
    enter_location_ph: "Enter City, District or Pincode (e.g. Bengaluru, Noida, 560001)",
    search_location: "Search Location",
    distance_away: "km away",
    get_directions: "🧭 Get Directions on Mappls",
    find_other_schemes: "← Find Other Schemes",
    back_home: "Back to Home",
    footer_motto: "More Awareness → Better Choices → Brighter Future",
    footer_copy: "© Scheme Compass • Government scheme discovery prototype",
  },
  ta: {
    brand_title: "ஸ்கீம்",
    brand_accent: "காம்பஸ்",
    brand_sub: "சரியான அரசு திட்டத்திற்கான உங்கள் வழிகாட்டி",
    nav_home: "முகப்பு",
    nav_find_schemes: "திட்டங்களை தேடுக",
    nav_how_it_works: "செயல்படும் முறை",
    nav_about: "எங்களைப் பற்றி",
    nav_help: "உதவி & ஆதரவு",
    gov_title: "இந்திய அரசு",
    gov_ministry: "சமூக நீதி மற்றும் அதிகாரமளித்தல் அமைச்சகம்",
    hero_eyebrow: "அரசு திட்டங்கள் கண்டறியும் தளம்",
    hero_title_1: "உங்களுக்கான சரியான",
    hero_title_2: "அரசு திட்டத்தைக்",
    hero_title_3: "கண்டறியவும்",
    hero_desc: "உங்கள் தேவைகள், தகுதிகள் மற்றும் இலக்குகளின் அடிப்படையில் நிதி மற்றும் கல்வி உதவி திட்டங்களை எளிதாகக் கண்டறியவும்.",
    hero_btn: "திட்டத்தைத் தேடுக",
    need_heading: "உங்களுக்கு என்ன உதவி தேவை?",
    need_sub: "ஒரு விருப்பத்தைத் தேர்ந்தெடுக்கவும், பொருத்தமான அரசு திட்டங்களை நாங்கள் வழிகாட்டுவோம்.",
    need_biz_title: "தொழில் தொடங்க",
    need_biz_desc: "புதிய தொழில் தொடங்க நிதி உதவிகளை ஆராயுங்கள்.",
    need_edu_title: "கல்வி உதவி",
    need_edu_desc: "கல்வி கடன்கள் மற்றும் நிதி உதவிகளைக் கண்டறியவும்.",
    need_growth_title: "தொழில் விரிவாக்கம்",
    need_growth_desc: "உங்கள் தொழிலை வளர்க்க ஆதரவைக் கண்டறியவும்.",
    need_money_title: "பிற நிதி தேவைகள்",
    need_money_desc: "பிற நிதி உதவி விருப்பங்களை ஆராயுங்கள்.",
    explore: "ஆராயுங்கள்",
    trust_gov_title: "அரசால் அங்கீகரிக்கப்பட்டது",
    trust_gov_desc: "அதிகாரப்பூர்வ திட்ட விவரங்கள்",
    trust_safe_title: "பாதுகாப்பானது",
    trust_safe_desc: "உங்கள் விவரங்கள் பாதுகாப்பானவை",
    trust_partners_title: "100+ கூட்டாளர்கள்",
    trust_partners_desc: "நிதி நெட்வொர்க் முழுவதும்",
    trust_coverage_title: "இந்திய அளவிலான சேவை",
    trust_coverage_desc: "இந்தியா முழுவதும் ஆதரவு",
    step1_eyebrow: "படி 1 / 2",
    step1_title: "நீங்கள் என்ன தேடுகிறீர்கள்?",
    step1_sub: "தகுதியான அரசு திட்டங்களை கண்டறிய உங்கள் தேவையை தேர்வு செய்யவும்.",
    continue: "தொடரவும்",
    form_title: "வணிக உதவி",
    form_sub: "பொருத்தமான திட்டங்களை அடையாளம் காண சில எளிய கேள்விகளுக்கு பதிலளிக்கவும்.",
    project_type_label: "திட்ட வகை / வணிக யோசனை",
    project_type_ph: "எ.கா. சில்லறை கடை, உற்பத்தி, பால் பண்ணை",
    project_cost_label: "மதிப்பிடப்பட்ட திட்ட செலவு",
    project_cost_ph: "₹ தொகையை உள்ளிடவும்",
    family_income_label: "ஆண்டு குடும்ப வருமானம்",
    family_income_ph: "₹ வருமானத்தை உள்ளிடவும்",
    social_category_label: "சமூகப் பிரிவு",
    social_category_sc: "பட்டியலிடப்பட்ட சாதியினர் (SC)",
    social_category_st: "பட்டியலிடப்பட்ட பழங்குடியினர் (ST)",
    social_category_obc: "இதர பிற்படுத்தப்பட்ட வகுப்பினர் (OBC)",
    social_category_gen: "பொது / பிற",
    state_label: "வாழும் மாநிலம்",
    state_ph: "உங்கள் மாநிலத்தை உள்ளிடவும் (எ.கா. தமிழ்நாடு)",
    natural_input_label: "அல்லது உங்கள் மொழியில் உங்கள் தேவையை விளக்கவும்:",
    natural_input_ph: "எ.கா. தமிழ்நாட்டில் மளிகைக் கடை தொடங்க 5 லட்சம் கடன் தேவை",
    find_matching_btn: "பொருந்தும் திட்டங்களைக் கண்டறியவும்",
    rec_evaluated: "மதிப்பிடப்பட்ட திட்டங்கள் · CONVEX & SARVAM NLU",
    rec_title: "பரிந்துரைக்கப்பட்ட திட்டங்கள்",
    rec_sub: "உங்கள் தகுதி மற்றும் இயற்கை மொழி நோக்கம் அடிப்படையில் மதிப்பிடப்பட்ட சிறந்த திட்டங்கள்.",
    status_eligible: "தகுதியுடையது",
    status_requires_verification: "சரிபார்ப்பு தேவை",
    status_ineligible: "தகுதியற்றது",
    gov_sector: "அரசு துறை",
    channel_partner: "சேவை கூட்டாளர்",
    max_benefit: "அதிகபட்ச பலன்",
    match_confidence: "பொருந்தும் நம்பிக்கை",
    reasons_label: "மதிப்பீட்டு காரணங்கள்",
    view_details: "திட்ட விவரங்களைக் காண்க",
    no_matching: "பொருந்தும் திட்டங்கள் எதுவும் கிடைக்கவில்லை",
    no_matching_sub: "உங்கள் தேடல் அளவுகோல்களை மாற்றி முயற்சிக்கவும்.",
    back_to_find: "மீண்டும் தேடலுக்கு செல்லவும்",
    scheme_details_title: "திட்ட விவரங்கள்",
    eligibility_docs_title: "தகுதி & தேவையான ஆவணங்கள்",
    documents: "தேவையான ஆவணங்கள்",
    fin_support_title: "நிதி உதவி & பலன்கள்",
    estimate_emi: "EMI கணக்கிடுக",
    find_nearby_partner: "அருகிலுள்ள கூட்டாளரைக் கண்டறியவும்",
    partners_title: "தகுதியான சேவை கூட்டாளர்கள்",
    partners_sub: "Mappls மூலம் கண்டறியப்பட்ட உண்மையான கிளைகள்",
    use_current_location: "📍 தற்போதைய இருப்பிடத்தைப் பயன்படுத்தவும்",
    getting_location: "உங்கள் இருப்பிடம் கண்டறியப்படுகிறது...",
    location_denied: "இருப்பிட அனுமதி மறுக்கப்பட்டது. கீழே உங்கள் ஊரை உள்ளிடவும்.",
    enter_location_ph: "நகரம் அல்லது அஞ்சல் குறியீட்டை உள்ளிடவும் (எ.கா. சென்னை, 600001)",
    search_location: "இருப்பிடத்தை தேடுக",
    distance_away: "கி.மீ தூரத்தில்",
    get_directions: "🧭 Mappls வழித்தடத்தைப் பெறுக",
    find_other_schemes: "← பிற திட்டங்களைத் தேடுக",
    back_home: "முகப்பிற்குச் செல்லவும்",
    footer_motto: "அதிக விழிப்புணர்வு → சிறந்த தேர்வுகள் → பிரகாசமான எதிர்காலம்",
    footer_copy: "© ஸ்கீம் காம்பஸ் • அரசு திட்ட கண்டுபிடிப்பு முன்மாதிரி",
  },
  hi: {
    brand_title: "स्कीम",
    brand_accent: "कंपास",
    brand_sub: "सही सरकारी योजना के लिए आपका मार्गदर्शक",
    nav_home: "मुख्य पृष्ठ",
    nav_find_schemes: "योजनाएं खोजें",
    nav_how_it_works: "यह कैसे काम करता है",
    nav_about: "हमारे बारे में",
    nav_help: "सहायता और सहायता",
    gov_title: "भारत सरकार",
    gov_ministry: "सामाजिक न्याय और अधिकारिता मंत्रालय",
    hero_eyebrow: "सरकारी योजना खोज पोर्टल",
    hero_title_1: "अपने लिए सही",
    hero_title_2: "सरकारी योजना",
    hero_title_3: "खोजें",
    hero_desc: "अपनी आवश्यकताओं, पात्रता और लक्ष्यों के आधार पर वित्तीय और शैक्षिक सहायता योजनाओं की आसानी से खोज करें।",
    hero_btn: "योजना खोजें",
    need_heading: "आपको किस सहायता की आवश्यकता है?",
    need_sub: "एक विकल्प चुनें और हम प्रासंगिक सरकारी योजनाओं के माध्यम से आपका मार्गदर्शन करेंगे।",
    need_biz_title: "व्यवसाय शुरू करें",
    need_biz_desc: "अपना व्यवसाय शुरू करने के लिए वित्तीय सहायता देखें।",
    need_edu_title: "शिक्षा सहायता",
    need_edu_desc: "शिक्षा ऋण और वित्तीय सहायता खोजें।",
    need_growth_title: "व्यापार का विस्तार करें",
    need_growth_desc: "अपने व्यवसाय को बढ़ाने के लिए सहायता खोजें।",
    need_money_title: "अन्य वित्तीय आवश्यकताएं",
    need_money_desc: "अन्य वित्तीय सहायता विकल्पों की खोज करें।",
    explore: "अन्वेषण करें",
    trust_gov_title: "सरकार द्वारा विश्वसनीय",
    trust_gov_desc: "आधिकारिक योजना जानकारी",
    trust_safe_title: "सुरक्षित और सुरक्षित",
    trust_safe_desc: "आपकी जानकारी सुरक्षित है",
    trust_partners_title: "100+ चैनल पार्टनर",
    trust_partners_desc: "वित्तीय नेटवर्क में",
    trust_coverage_title: "पूरे भारत में कवरेज",
    trust_coverage_desc: "पूरे भारत में सहायता",
    step1_eyebrow: "चरण 1 / 2",
    step1_title: "आप क्या खोज रहे हैं?",
    step1_sub: "पात्र सरकारी योजनाओं को खोजने के लिए अपनी आवश्यकता चुनें।",
    continue: "जारी रखें",
    form_title: "व्यवसाय सहायता",
    form_sub: "प्रासंगिक योजनाओं की पहचान करने के लिए कुछ सरल प्रश्नों के उत्तर दें।",
    project_type_label: "परियोजना प्रकार / व्यापार विचार",
    project_type_ph: "जैसे रिटेल दुकान, विनिर्माण, डेयरी फॉर्म",
    project_cost_label: "अनुमानित परियोजना लागत",
    project_cost_ph: "₹ राशि दर्ज करें",
    family_income_label: "वार्षिक पारिवारिक आय",
    family_income_ph: "₹ वार्षिक आय दर्ज करें",
    social_category_label: "सामाजिक श्रेणी",
    social_category_sc: "अनुसूचित जाति (SC)",
    social_category_st: "अनुसूचित जनजाति (ST)",
    social_category_obc: "अन्य पिछड़ा वर्ग (OBC)",
    social_category_gen: "सामान्य / अन्य",
    state_label: "आवासी राज्य",
    state_ph: "अपना राज्य दर्ज करें (जैसे उत्तर प्रदेश, तमिलनाडु)",
    natural_input_label: "या अपनी भाषा में अपनी आवश्यकता का वर्णन करें:",
    natural_input_ph: "जैसे मुझे उत्तर प्रदेश में किराने की दुकान खोलने के लिए 5 लाख का ऋण चाहिए",
    find_matching_btn: "मैचिंग योजनाएं खोजें",
    rec_evaluated: "मूल्यांकन की गई योजनाएं · CONVEX & SARVAM NLU",
    rec_title: "अनुशंसित योजनाएं",
    rec_sub: "आपकी पात्रता और प्राकृतिक भाषा के आधार पर मूल्यांकित शीर्ष योजनाएं।",
    status_eligible: "पात्र (ELIGIBLE)",
    status_requires_verification: "सत्यापन आवश्यक (REQUIRES VERIFICATION)",
    status_ineligible: "अपात्र (INELIGIBLE)",
    gov_sector: "सरकारी क्षेत्र",
    channel_partner: "चैनल पार्टनर",
    max_benefit: "अधिकतम लाभ",
    match_confidence: "मैच आत्मविश्वास",
    reasons_label: "मूल्यांकन के कारण",
    view_details: "योजना विवरण देखें",
    no_matching: "कोई मेल खाने वाली योजना नहीं मिली",
    no_matching_sub: "अपने खोज मानदंडों को समायोजित करने का प्रयास करें।",
    back_to_find: "वापस योजना खोजें पर जाएं",
    scheme_details_title: "योजना विवरण",
    eligibility_docs_title: "पात्रता और आवश्यक दस्तावेज",
    documents: "आवश्यक दस्तावेज",
    fin_support_title: "वित्तीय सहायता और लाभ",
    estimate_emi: "EMI का अनुमान लगाएं",
    find_nearby_partner: "निकटतम पार्टनर खोजें",
    partners_title: "पात्र चैनल पार्टनर",
    partners_sub: "Mappls एकीकरण के माध्यम से खोजे गए वास्तविक स्थान",
    use_current_location: "📍 वर्तमान स्थान का उपयोग करें",
    getting_location: "आपका स्थान खोजा जा रहा है...",
    location_denied: "स्थान की अनुमति अस्वीकृत। कृपया नीचे अपना शहर दर्ज करें।",
    enter_location_ph: "शहर या पिनकोड दर्ज करें (जैसे नोएडा, दिल्ली, 110001)",
    search_location: "स्थान खोजें",
    distance_away: "किमी दूर",
    get_directions: "🧭 Mappls पर दिशा-निर्देश प्राप्त करें",
    find_other_schemes: "← अन्य योजनाएं खोजें",
    back_home: "मुख्य पृष्ठ पर जाएं",
    footer_motto: "अधिक जागरूकता → बेहतर विकल्प → उज्ज्वल भविष्य",
    footer_copy: "© स्कीम कंपास • सरकारी योजना खोज प्रोटोटाइप",
  },
  kn: {
    brand_title: "ಸ್ಕೀಮ್",
    brand_accent: "ಕಂಪಾಸ್",
    brand_sub: "ಸರಿಯಾದ ಸರ್ಕಾರಿ ಯೋಜನೆಗೆ ನಿಮ್ಮ ಮಾರ್ಗದರ್ಶಿ",
    nav_home: "ಮುಖಪುಟ",
    nav_find_schemes: "ಯೋಜನೆಗಳನ್ನು ಹುಡುಕಿ",
    nav_how_it_works: "ಇದು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ",
    nav_about: "ನಮ್ಮ ಬಗ್ಗೆ",
    nav_help: "ಸಹಾಯ ಮತ್ತು ಬೆಂಬಲ",
    gov_title: "ಭಾರತ ಸರ್ಕಾರ",
    gov_ministry: "ಸಾಮಾಜಿಕ ನ್ಯಾಯ ಮತ್ತು ಸಬಲೀಕರಣ ಸಚಿವಾಲಯ",
    hero_eyebrow: "ಸರ್ಕಾರಿ ಯೋಜನೆ ಅನ್ವೇಷಣೆ ಪೋರ್ಟಲ್",
    hero_title_1: "ನಿಮಗಾಗಿ ಸರಿಯಾದ",
    hero_title_2: "ಸರ್ಕಾರಿ ಯೋಜನೆಯನ್ನು",
    hero_title_3: "ಹುಡುಕಿ",
    hero_desc: "ನಿಮ್ಮ ಅಗತ್ಯಗಳು, ಅರ್ಹತೆಗಳು ಮತ್ತು ಗುರಿಗಳ ಆಧಾರದ ಮೇಲೆ ಹಣಕಾಸು ಮತ್ತು ಶೈಕ್ಷಣಿಕ ಸಹಾಯ ಯೋಜನೆಗಳನ್ನು ಸುಲಭವಾಗಿ ಕಂಡುಕೊಳ್ಳಿ.",
    hero_btn: "ಯೋಜನೆಯನ್ನು ಹುಡುಕಿ",
    need_heading: "ನಿಮಗೆ ಯಾವ ಸಹಾಯ ಬೇಕು?",
    need_sub: "ಒಂದು ಆಯ್ಕೆಯನ್ನು ಆರಿಸಿ ಮತ್ತು ನಾವು ಸೂಕ್ತವಾದ ಸರ್ಕಾರಿ ಯೋಜನೆಗಳ ಮೂಲಕ ನಿಮಗೆ ಮಾರ್ಗದರ್ಶನ ನೀಡುತ್ತೇವೆ.",
    need_biz_title: "ವ್ಯಾಪಾರ ಪ್ರಾರಂಭಿಸಿ",
    need_biz_desc: "ನಿಮ್ಮ ವ್ಯಾಪಾರವನ್ನು ಪ್ರಾರಂಭಿಸಲು ಹಣಕಾಸಿನ ಸಹಾಯವನ್ನು ಅನ್ವೇಷಿಸಿ.",
    need_edu_title: "ಶಿಕ್ಷಣ ಸಹಾಯ",
    need_edu_desc: "ಶಿಕ್ಷಣ ಸಾಲಗಳು ಮತ್ತು ಹಣಕಾಸಿನ ನೆರವು ಕಂಡುಕೊಳ್ಳಿ.",
    need_growth_title: "ವ್ಯಾಪಾರ ವಿಸ್ತರಣೆ",
    need_growth_desc: "ನಿಮ್ಮ ವ್ಯಾಪಾರವನ್ನು ಬೆಳೆಸಲು ಬೆಂಬಲವನ್ನು ಹುಡುಕಿ.",
    need_money_title: "ಇತರ ಹಣಕಾಸು ಅಗತ್ಯಗಳು",
    need_money_desc: "ಇತರ ಹಣಕಾಸಿನ ನೆರವಿನ ಆಯ್ಕೆಗಳನ್ನು ಅನ್ವೇಷಿಸಿ.",
    explore: "ಅನ್ವೇಷಿಸಿ",
    trust_gov_title: "ಸರ್ಕಾರದಿಂದ ನಂಬಿಕಾರ್ಹ",
    trust_gov_desc: "ಅಧಿಕೃತ ಯೋಜನಾ ಮಾಹಿತಿ",
    trust_safe_title: "ಸುರಕ್ಷಿತ ಮತ್ತು ಭದ್ರ",
    trust_safe_desc: "ನಿಮ್ಮ ಮಾಹಿತಿ ಸುರಕ್ಷಿತವಾಗಿದೆ",
    trust_partners_title: "100+ ಚಾನೆಲ್ ಪಾಲುದಾರರು",
    trust_partners_desc: "ಹಣಕಾಸು ಜಾಲದಾದ್ಯಂತ",
    trust_coverage_title: "ಸಂಪೂರ್ಣ ಭಾರತದಾದ್ಯಂತ ಸೇವೆ",
    trust_coverage_desc: "ಭಾರತದಾದ್ಯಂತ ಬೆಂಬಲ",
    step1_eyebrow: "ಹಂತ 1 / 2",
    step1_title: "ನೀವು ಏನನ್ನು ಹುಡುಕುತ್ತಿದ್ದೀರಿ?",
    step1_sub: "ಅರ್ಹ ಸರ್ಕಾರಿ ಯೋಜನೆಗಳನ್ನು ಅನ್ವೇಷಿಸಲು ನಿಮ್ಮ ಅಗತ್ಯವನ್ನು ಆಯ್ಕೆಮಾಡಿ.",
    continue: "ಮುಂದುವರಿಸಿ",
    form_title: "ವ್ಯಾಪಾರ ನೆರವು",
    form_sub: "ಸೂಕ್ತ ಯೋಜನೆಗಳನ್ನು ಗುರುತಿಸಲು ಕೆಲವು ಸರಳ ಪ್ರಶ್ನೆಗಳಿಗೆ ಉತ್ತರಿಸಿ.",
    project_type_label: "ಯೋಜನೆಯ ಪ್ರಕಾರ / ವ್ಯಾಪಾರದ ಕಲ್ಪನೆ",
    project_type_ph: "ಉದಾ. ಚಿಲ್ಲರೆ ಅಂಗಡಿ, ಉತ್ಪಾದನೆ, ಹಾಲಿನ ಫಾರ್ಮ್",
    project_cost_label: "ಅಂದಾಜು ಯೋಜನಾ ವೆಚ್ಚ",
    project_cost_ph: "₹ ಮೊತ್ತವನ್ನು ನಮೂದಿಸಿ",
    family_income_label: "ವಾರ್ಷಿಕ ಕೌಟುಂಬಿಕ ಆದಾಯ",
    family_income_ph: "₹ ವಾರ್ಷಿಕ ಆದಾಯವನ್ನು ನಮೂದಿಸಿ",
    social_category_label: "ಸಾಮಾಜಿಕ ವರ್ಗ",
    social_category_sc: "ಪರಿಶಿಷ್ಟ ಜಾತಿ (SC)",
    social_category_st: "ಪರಿಶಿಷ್ಟ ಪಂಗಡ (ST)",
    social_category_obc: "ಇತರ ಹಿಂದುಳಿದ ವರ್ಗ (OBC)",
    social_category_gen: "ಸಾಮಾನ್ಯ / ಇತರ",
    state_label: "ನಿವಾಸಿ ರಾಜ್ಯ",
    state_ph: "ನಿಮ್ಮ ರಾಜ್ಯವನ್ನು ನಮೂದಿಸಿ (ಉದಾ. ಕರ್ನಾಟಕ)",
    natural_input_label: "ಅಥವಾ ನಿಮ್ಮ ಸ್ವಂತ ಭಾಷೆಯಲ್ಲಿ ನಿಮ್ಮ ಅಗತ್ಯವನ್ನು ವಿವರಿಸಿ:",
    natural_input_ph: "ಉದಾ. ಕರ್ನಾಟಕದಲ್ಲಿ ಕಿರಾಣಿ ಅಂಗಡಿ ತೆರೆಯಲು ನನಗೆ 5 ಲಕ್ಷ ಸಾಲ ಬೇಕು",
    find_matching_btn: "ಸರಿಯಾಗಿ ಹೊಂದುವ ಯೋಜನೆಗಳನ್ನು ಹುಡುಕಿ",
    rec_evaluated: "ಮೌಲ್ಯಮಾಪನ ಮಾಡಲಾದ ಯೋಜನೆಗಳು · CONVEX & SARVAM NLU",
    rec_title: "ಶಿಫಾರಸು ಮಾಡಲಾದ ಯೋಜನೆಗಳು",
    rec_sub: "ನಿಮ್ಮ ಅರ್ಹತೆ ಮತ್ತು ನೈಸರ್ಗಿಕ ಭಾಷೆಯ ಆಧಾರದ ಮೇಲೆ ಮೌಲ್ಯಮಾಪನ ಮಾಡಲಾದ ಅತ್ಯುತ್ತಮ ಯೋಜನೆಗಳು.",
    status_eligible: "ಅರ್ಹರು (ELIGIBLE)",
    status_requires_verification: "ಪರಿಶೀಲನೆ ಅಗತ್ಯವಿದೆ (REQUIRES VERIFICATION)",
    status_ineligible: "ಅನರ್ಹರು (INELIGIBLE)",
    gov_sector: "ಸರ್ಕಾರಿ ವಲಯ",
    channel_partner: "ಚಾನೆಲ್ ಪಾಲುದಾರ",
    max_benefit: "ಗರಿಷ್ಠ ಪ್ರಯೋಜನ",
    match_confidence: "ಹೊಂದಾಣಿಕೆಯ ವಿಶ್ವಾಸಾರ್ಹತೆ",
    reasons_label: "ಮೌಲ್ಯಮಾಪನದ ಕಾರಣಗಳು",
    view_details: "ಯೋಜನೆಯ ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಿ",
    no_matching: "ಯಾವುದೇ ಸೂಕ್ತ ಯೋಜನೆಗಳು ಕಂಡುಬಂದಿಲ್ಲ",
    no_matching_sub: "ನಿಮ್ಮ ಹುಡುಕಾಟದ ಮಾನದಂಡಗಳನ್ನು ಬದಲಾಯಿಸಿ ಪ್ರಯತ್ನಿಸಿ.",
    back_to_find: "ಹಿಂತಿರುಗಿ ಯೋಜನೆ ಹುಡುಕಿ",
    scheme_details_title: "ಯೋಜನೆಯ ವಿವರಗಳು",
    eligibility_docs_title: "ಅರ್ಹತೆ ಮತ್ತು ಅಗತ್ಯ ದಾಖಲೆಗಳು",
    documents: "ಅಗತ್ಯ ದಾಖಲೆಗಳು",
    fin_support_title: "ಹಣಕಾಸು ನೆರವು ಮತ್ತು ಪ್ರಯೋಜನಗಳು",
    estimate_emi: "EMI ಅಂದಾಜಿಸಿ",
    find_nearby_partner: "ಹತ್ತಿರದ ಚಾನೆಲ್ ಪಾಲುದಾರರನ್ನು ಹುಡುಕಿ",
    partners_title: "ಅರ್ಹ ಚಾನೆಲ್ ಪಾಲುದಾರರು",
    partners_sub: "Mappls ಸಂಯೋಜನೆಯ ಮೂಲಕ ಪತ್ತೆಯಾದ ನೈಜ ಶಾಖೆಗಳು",
    use_current_location: "📍 ಪ್ರಸ್ತುತ ಸ್ಥಳವನ್ನು ಬಳಸಿ",
    getting_location: "ನಿಮ್ಮ ಸ್ಥಳವನ್ನು ಪತ್ತೆಮಾಡಲಾಗುತ್ತಿದೆ...",
    location_denied: "ಸ್ಥಳದ ಅನುಮತಿ ನಿರಾಕರಿಸಲಾಗಿದೆ. ದಯವಿಟ್ಟು ನಿಮ್ಮ ನಗರವನ್ನು ನಮೂದಿಸಿ.",
    enter_location_ph: "ನಗರ ಅಥವಾ ಪಿನ್‌ಕೋಡ್ ನಮೂದಿಸಿ (ಉದಾ. ಬೆಂಗಳೂರು, ಮೈಸೂರು, 560001)",
    search_location: "ಸ್ಥಳವನ್ನು ಹುಡುಕಿ",
    distance_away: "ಕಿಮೀ ದೂರದಲ್ಲಿದೆ",
    get_directions: "🧭 Mappls ನಲ್ಲಿ ಮಾರ್ಗಸೂಚಿ ಪಡೆಯಿರಿ",
    find_other_schemes: "← ಇತರ ಯೋಜನೆಗಳನ್ನು ಹುಡುಕಿ",
    back_home: "ಮುಖಪುಟಕ್ಕೆ ಹಿಂತಿರುಗಿ",
    footer_motto: "ಹೆಚ್ಚಿನ ಅರಿವು → ಉತ್ತಮ ಆಯ್ಕೆಗಳು → ಉಜ್ವಲ ಭವಿಷ್ಯ",
    footer_copy: "© ಸ್ಕೀಮ್ ಕಂಪಾಸ್ • ಸರ್ಕಾರಿ ಯೋಜನೆ ಅನ್ವೇಷಣೆ ಪ್ರೋಟೋಟೈಪ್",
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState("en");

  useEffect(() => {
    const saved = localStorage.getItem("sc_language");
    if (saved && ["en", "ta", "hi", "kn"].includes(saved)) {
      setLang(saved);
    }
  }, []);

  const changeLanguage = (newLang) => {
    if (["en", "ta", "hi", "kn"].includes(newLang)) {
      setLang(newLang);
      localStorage.setItem("sc_language", newLang);
    }
  };

  const t = (key) => {
    return translations[lang]?.[key] || translations.en?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    return {
      lang: "en",
      changeLanguage: () => {},
      t: (key) => key,
    };
  }
  return context;
}
