"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

const translations = {
  en: {
    brand_title: "Scheme",
    brand_accent: "Compass",
    brand_sub: "Your Guide to the Right Government Scheme",
    nav_home: "Home",
    nav_find_schemes: "Find Schemes",
    nav_how_it_works: "How It Works",
    nav_about: "About",
    nav_help: "Help & Support",
    nav_calculator: "Loan Calculator",
    nav_partners: "Channel Partners",
    gov_title: "Government of India",
    gov_ministry: "Ministry of Social Justice and Empowerment",
    hero_eyebrow: "SCHEME DISCOVERY PORTAL",
    hero_title_1: "Find the Right",
    hero_title_2: "Government Scheme",
    hero_title_3: "for You",
    hero_desc: "Discover financial and educational support schemes based on your needs, eligibility and goals — simply and clearly.",
    hero_btn: "Find a Scheme",
    need_heading: "What do you need help with?",
    need_sub: "Choose an option and we’ll guide you through the relevant government schemes.",
    need_biz_title: "Start a Business",
    need_biz_desc: "Explore financial support to start your business.",
    need_edu_title: "Education",
    need_edu_desc: "Find education loans and financial assistance.",
    need_growth_title: "Expand My Business",
    need_growth_desc: "Find support to grow and strengthen your business.",
    need_money_title: "Other Financial Need",
    need_money_desc: "Explore other financial assistance options.",
    explore: "Explore",
    trust_gov_title: "Trusted by Government",
    trust_gov_desc: "Official scheme information",
    trust_safe_title: "Safe & Secure",
    trust_safe_desc: "Your information matters",
    trust_partners_title: "100+ Channel Partners",
    trust_partners_desc: "Across financial networks",
    trust_coverage_title: "Pan India Coverage",
    trust_coverage_desc: "Support across India",
    step1_eyebrow: "STEP 1 OF 2",
    step1_title: "What are you looking for?",
    step1_sub: "Select your requirement to discover eligible government schemes.",
    continue: "Continue",
    ai_badge: "SCHEME COMPASS AI",
    natural_form_title: "Tell us what you need",
    natural_form_desc: "Describe your need in your own words. Our AI will understand it and find relevant government schemes.",
    guided_form_title: "Guided Application Form",
    guided_form_desc: "Fill in your details manually to discover matching government schemes.",
    natural_input_ph: 'e.g. "I need a ₹2.5 lakh business loan to start a chicken shop in Kerala. I am SC and my annual family income is ₹1.5 lakh."',
    understanding_request: "Understanding your request…",
    find_matching_btn: "Find Matching Schemes",
    enter_manually: "Enter details manually with Guided Form",
    back_to_natural: "← Back to Natural Language Input",
    here_is_what_understood: "✨ Here's what I understood",
    business_project: "Business / Project",
    amount: "Amount",
    annual_income: "Annual Income",
    social_category: "Social Category",
    state_prompt: "📍 Which state are you applying from? *",
    error_describe_need: "Please describe your financial need or project requirement.",
    error_select_state: "Which state are you applying from?",
    error_nlu_failed: "Sorry, we couldn't understand your request right now. Please try again.",
    error_select_category: "Please select your social category.",
    error_valid_cost: "Please enter a valid positive project cost / required amount.",
    error_valid_income: "Please enter a valid annual family income.",
    error_valid_state: "Please enter your resident state.",
    project_type_label: "Project type / Business idea",
    project_cost_label: "Required Amount (₹) *",
    family_income_label: "Annual Family Income (₹) *",
    social_category_label: "Social Category *",
    state_label: "Resident State *",
    rec_evaluated: "SCHEMES EVALUATED",
    rec_title: "Recommended Schemes",
    rec_sub: "Based on your criteria and eligibility, here are the top evaluated scheme recommendations.",
    finding_best_schemes: "Finding the best schemes for you…",
    loading_step_1: "Understanding your request",
    loading_step_2: "Finding relevant schemes",
    loading_step_3: "Checking eligibility",
    loading_step_4: "Preparing your results",
    status_eligible: "ELIGIBLE",
    status_requires_verification: "REQUIRES VERIFICATION",
    status_ineligible: "INELIGIBLE",
    gov_sector: "Government Sector",
    channel_partner: "Channel Partner",
    max_benefit: "Maximum Benefit",
    match_confidence: "Match Confidence",
    view_details: "View Scheme Details",
    no_matching: "No Matching Schemes Found",
    no_matching_sub: "Try adjusting your search criteria or purpose.",
    back_to_find: "Back to Find Scheme",
    back_to_results: "← Back to Results",
    related_schemes: "Other Matching Schemes",
    scheme_details_title: "SCHEME DETAILS",
    eligibility_docs_title: "Eligibility & Documents Required",
    documents: "Documents Required",
    fin_support_title: "Financial Support & Benefit",
    estimate_emi: "Estimate EMI",
    find_nearby_partner: "Find Channel Partners",
    partners_title: "Find a Nearby Partner",
    partners_sub: "Find the nearest physical branch or service point for this scheme.",
    searching_near: "📍 Searching near:",
    use_current_location: "📍 Use Current Location",
    getting_location: "Detecting your location...",
    location_denied: "Location permission denied or unavailable. Enter location manually below.",
    enter_location_ph: "Enter City, District or Pincode (e.g. Bengaluru, Noida, 560001)",
    search_location: "Search Location",
    filter_by_institution: "Filter by Institution Type",
    distance_away: "km away",
    get_directions: "🧭 Open Directions in Mappls",
    mappls_pin: "Mappls Pin",
    find_other_schemes: "← Find Other Schemes",
    back_home: "Back to Home",
    footer_motto: "More Awareness → Better Choices → Brighter Future",
    footer_copy: "© Scheme Compass • Government scheme discovery prototype",
  },
  ta: {
    brand_title: "ஸ்கீம்",
    brand_accent: "காம்பஸ்",
    brand_sub: "சரியான அரசு திட்டத்திற்கான உங்கள் வழிகாட்டி",
    nav_home: "முகப்பு",
    nav_find_schemes: "திட்டங்களை தேடுக",
    nav_how_it_works: "செயல்படும் முறை",
    nav_about: "எங்களைப் பற்றி",
    nav_help: "உதவி & ஆதரவு",
    nav_calculator: "கடன் கணக்கீட்டாளர்",
    nav_partners: "சேவை கூட்டாளர்கள்",
    gov_title: "இந்திய அரசு",
    gov_ministry: "சமூக நீதி மற்றும் அதிகாரமளித்தல் அமைச்சகம்",
    hero_eyebrow: "அரசு திட்டங்கள் கண்டறியும் தளம்",
    hero_title_1: "உங்களுக்கான சரியான",
    hero_title_2: "அரசு திட்டத்தைக்",
    hero_title_3: "கண்டறியவும்",
    hero_desc: "உங்கள் தேவைகள், தகுதிகள் மற்றும் இலக்குகளின் அடிப்படையில் நிதி மற்றும் கல்வி உதவி திட்டங்களை எளிதாகக் கண்டறியவும்.",
    hero_btn: "திட்டத்தைத் தேடுக",
    need_heading: "உங்களுக்கு என்ன உதவி தேவை?",
    need_sub: "ஒரு விருப்பத்தைத் தேர்ந்தெடுக்கவும், பொருத்தமான அரசு திட்டங்களை நாங்கள் வழிகாட்டுவோம்.",
    need_biz_title: "தொழில் தொடங்க",
    need_biz_desc: "புதிய தொழில் தொடங்க நிதி உதவிகளை ஆராயுங்கள்.",
    need_edu_title: "கல்வி உதவி",
    need_edu_desc: "கல்வி கடன்கள் மற்றும் நிதி உதவிகளைக் கண்டறியவும்.",
    need_growth_title: "தொழில் விரிவாக்கம்",
    need_growth_desc: "உங்கள் தொழிலை வளர்க்க ஆதரவைக் கண்டறியவும்.",
    need_money_title: "பிற நிதி தேவைகள்",
    need_money_desc: "பிற நிதி உதவி விருப்பங்களை ஆராயுங்கள்.",
    explore: "ஆராயுங்கள்",
    trust_gov_title: "அரசால் அங்கீகரிக்கப்பட்டது",
    trust_gov_desc: "அதிகாரப்பூர்வ திட்ட விவரங்கள்",
    trust_safe_title: "பாதுகாப்பானது",
    trust_safe_desc: "உங்கள் விவரங்கள் பாதுகாப்பானவை",
    trust_partners_title: "100+ கூட்டாளர்கள்",
    trust_partners_desc: "நிதி நெட்வொர்க் முழுவதும்",
    trust_coverage_title: "இந்திய அளவிலான சேவை",
    trust_coverage_desc: "இந்தியா முழுவதும் ஆதரவு",
    step1_eyebrow: "படி 1 / 2",
    step1_title: "நீங்கள் என்ன தேடுகிறீர்கள்?",
    step1_sub: "தகுதியான அரசு திட்டங்களை கண்டறிய உங்கள் தேவையை தேர்வு செய்யவும்.",
    continue: "தொடரவும்",
    ai_badge: "ஸ்கீம் காம்பஸ் AI",
    natural_form_title: "உங்களுக்கு என்ன தேவை என்று கூறுங்கள்",
    natural_form_desc: "உங்கள் சொந்த வார்த்தைகளில் உங்கள் தேவையை விவரியுங்கள். எங்கள் AI அதை புரிந்து கொண்டு பொருத்தமான திட்டங்களை கண்டறியும்.",
    guided_form_title: "வழிகாட்டப்பட்ட விண்ணப்பப் படிவம்",
    guided_form_desc: "பொருந்தும் அரசு திட்டங்களை கண்டறிய உங்கள் விவரங்களை கைமுறையாக நிரப்பவும்.",
    natural_input_ph: 'எ.கா. "கேரளாவில் கோழிப் பண்ணை தொடங்க 2.5 லட்சம் கடன் தேவை. எனது வருமானம் 1.5 லட்சம்."',
    understanding_request: "உங்கள் கோரிக்கையைப் புரிந்துகொள்கிறது…",
    find_matching_btn: "பொருந்தும் திட்டங்களைக் கண்டறியவும்",
    enter_manually: "படிவத்தின் மூலம் கைமுறையாக உள்ளிடவும்",
    back_to_natural: "← இயற்கை மொழி உள்ளீட்டிற்கு திரும்பு",
    here_is_what_understood: "✨ நான் புரிந்துகொண்டது இதுதான்",
    business_project: "தொழில் / திட்டம்",
    amount: "தொகை",
    annual_income: "ஆண்டு வருமானம்",
    social_category: "சமூகப் பிரிவு",
    state_prompt: "📍 நீங்கள் எந்த மாநிலத்திலிருந்து விண்ணப்பிக்கிறீர்கள்? *",
    error_describe_need: "உங்கள் நிதித் தேவை அல்லது திட்டத் தேவையை விவரியுங்கள்.",
    error_select_state: "நீங்கள் எந்த மாநிலத்திலிருந்து விண்ணப்பிக்கிறீர்கள்?",
    error_nlu_failed: "மன்னிக்கவும், இப்போது உங்கள் கோரிக்கையைப் புரிந்துகொள்ள முடியவில்லை. மீண்டும் முயற்சிக்கவும்.",
    error_select_category: "உங்கள் சமூகப் பிரிவைத் தேர்ந்தெடுக்கவும்.",
    error_valid_cost: "செல்லுபடியாகும் திட்ட செலவை உள்ளிடவும்.",
    error_valid_income: "செல்லுபடியாகும் குடும்ப வருமானத்தை உள்ளிடவும்.",
    error_valid_state: "உங்கள் மாநிலத்தை உள்ளிடவும்.",
    project_type_label: "திட்ட வகை / வணிக யோசனை",
    project_cost_label: "தேவையான தொகை (₹) *",
    family_income_label: "ஆண்டு குடும்ப வருமானம் (₹) *",
    social_category_label: "சமூகப் பிரிவு *",
    state_label: "வாழும் மாநிலம் *",
    rec_evaluated: "திட்டங்கள் மதிப்பிடப்பட்டன",
    rec_title: "பரிந்துரைக்கப்பட்ட திட்டங்கள்",
    rec_sub: "உங்கள் தகுதி மற்றும் நோக்கம் அடிப்படையில் மதிப்பிடப்பட்ட சிறந்த திட்டங்கள்.",
    finding_best_schemes: "உங்களுக்கான சிறந்த திட்டங்களைக் கண்டறிகிறது…",
    loading_step_1: "உங்கள் கோரிக்கையைப் புரிந்துகொள்கிறது",
    loading_step_2: "பொருத்தமான திட்டங்களைக் கண்டறிகிறது",
    loading_step_3: "தகுதியைச் சரிபார்க்கிறது",
    loading_step_4: "முடிவுகளைத் தயார் செய்கிறது",
    status_eligible: "தகுதியுடையது",
    status_requires_verification: "சரிபார்ப்பு தேவை",
    status_ineligible: "தகுதியற்றது",
    gov_sector: "அரசு துறை",
    channel_partner: "சேவை கூட்டாளர்",
    max_benefit: "அதிகபட்ச பலன்",
    match_confidence: "பொருந்தும் நம்பிக்கை",
    view_details: "திட்ட விவரங்களைக் காண்க",
    no_matching: "பொருந்தும் திட்டங்கள் எதுவும் கிடைக்கவில்லை",
    no_matching_sub: "உங்கள் தேடல் அளவுகோல்களை மாற்றி முயற்சிக்கவும்.",
    back_to_find: "மீண்டும் தேடலுக்கு செல்லவும்",
    back_to_results: "← முடிவுகளுக்குத் திரும்பு",
    related_schemes: "பிற பொருந்தும் திட்டங்கள்",
    scheme_details_title: "திட்ட விவரங்கள்",
    eligibility_docs_title: "தகுதி & தேவையான ஆவணங்கள்",
    documents: "தேவையான ஆவணங்கள்",
    fin_support_title: "நிதி உதவி & பலன்கள்",
    estimate_emi: "EMI கணக்கிடுக",
    find_nearby_partner: "சேவை கூட்டாளர்களைத் தேடுக",
    partners_title: "அருகிலுள்ள கூட்டாளரைக் கண்டறியவும்",
    partners_sub: "இந்த திட்டத்திற்கான அருகிலுள்ள கிளை அல்லது சேவை மையத்தைக் கண்டறியவும்.",
    searching_near: "📍 இதன் அருகில் தேடுகிறது:",
    use_current_location: "📍 தற்போதைய இருப்பிடத்தைப் பயன்படுத்தவும்",
    getting_location: "உங்கள் இருப்பிடம் கண்டறியப்படுகிறது...",
    location_denied: "இருப்பிட அனுமதி மறுக்கப்பட்டது. கீழே உங்கள் ஊரை உள்ளிடவும்.",
    enter_location_ph: "நகரம் அல்லது அஞ்சல் குறியீட்டை உள்ளிடவும் (எ.கா. சென்னை, 600001)",
    search_location: "இருப்பிடத்தை தேடுக",
    filter_by_institution: "நிறுவன வகை வாரியாக வடிக்கவும்",
    distance_away: "கி.மீ தூரத்தில்",
    get_directions: "🧭 Mappls இல் வழித்தடத்தைத் திறக்கவும்",
    mappls_pin: "Mappls பின்",
    find_other_schemes: "← பிற திட்டங்களைத் தேடுக",
    back_home: "முகப்பிற்குச் செல்லவும்",
    footer_motto: "அதிக விழிப்புணர்வு → சிறந்த தேர்வுகள் → பிரகாசமான எதிர்காலம்",
    footer_copy: "© ஸ்கீம் காம்பஸ் • அரசு திட்ட கண்டுபிடிப்பு முன்மாதிரி",
  },
  hi: {
    brand_title: "स्कीम",
    brand_accent: "कंपास",
    brand_sub: "सही सरकारी योजना के लिए आपका मार्गदर्शक",
    nav_home: "मुख्य पृष्ठ",
    nav_find_schemes: "योजनाएं खोजें",
    nav_how_it_works: "यह कैसे काम करता है",
    nav_about: "हमारे बारे में",
    nav_help: "सहायता और सहायता",
    nav_calculator: "ऋण कैलकुलेटर",
    nav_partners: "चैनल पार्टनर",
    gov_title: "भारत सरकार",
    gov_ministry: "सामाजिक न्याय और अधिकारिता मंत्रालय",
    hero_eyebrow: "सरकारी योजना खोज पोर्टल",
    hero_title_1: "अपने लिए सही",
    hero_title_2: "सरकारी योजना",
    hero_title_3: "खोजें",
    hero_desc: "अपनी आवश्यकताओं, पात्रता और लक्ष्यों के आधार पर वित्तीय और शैक्षिक सहायता योजनाओं की आसानी से खोज करें।",
    hero_btn: "योजना खोजें",
    need_heading: "आपको किस सहायता की आवश्यकता है?",
    need_sub: "एक विकल्प चुनें और हम प्रासंगिक सरकारी योजनाओं के माध्यम से आपका मार्गदर्शन करेंगे।",
    need_biz_title: "व्यवसाय शुरू करें",
    need_biz_desc: "अपना व्यवसाय शुरू करने के लिए वित्तीय सहायता देखें।",
    need_edu_title: "शिक्षा सहायता",
    need_edu_desc: "शिक्षा ऋण और वित्तीय सहायता खोजें।",
    need_growth_title: "व्यापार का विस्तार करें",
    need_growth_desc: "अपने व्यवसाय को बढ़ाने के लिए सहायता खोजें।",
    need_money_title: "अन्य वित्तीय आवश्यकताएं",
    need_money_desc: "अन्य वित्तीय सहायता विकल्पों की खोज करें।",
    explore: "अन्वेषण करें",
    trust_gov_title: "सरकार द्वारा विश्वसनीय",
    trust_gov_desc: "आधिकारिक योजना जानकारी",
    trust_safe_title: "सुरक्षित और सुरक्षित",
    trust_safe_desc: "आपकी जानकारी सुरक्षित है",
    trust_partners_title: "100+ चैनल पार्टनर",
    trust_partners_desc: "वित्तीय नेटवर्क में",
    trust_coverage_title: "पूरे भारत में कवरेज",
    trust_coverage_desc: "पूरे भारत में सहायता",
    step1_eyebrow: "चरण 1 / 2",
    step1_title: "आप क्या खोज रहे हैं?",
    step1_sub: "पात्र सरकारी योजनाओं को खोजने के लिए अपनी आवश्यकता चुनें।",
    continue: "जारी रखें",
    ai_badge: "स्कीम कंपास AI",
    natural_form_title: "बताएं कि आपको क्या चाहिए",
    natural_form_desc: "अपने शब्दों में अपनी आवश्यकता का वर्णन करें। हमारा AI इसे समझेगा और प्रासंगिक योजनाएं खोजेगा।",
    guided_form_title: "मार्गदर्शित आवेदन फॉर्म",
    guided_form_desc: "मैचिंग सरकारी योजनाओं की खोज के लिए अपने विवरण मैन्युअल रूप से भरें।",
    natural_input_ph: 'जैसे "केरल में पोल्ट्री फार्म शुरू करने के लिए 2.5 लाख का ऋण चाहिए। वार्षिक आय 1.5 लाख है।"',
    understanding_request: "आपकी आवश्यकता को समझा जा रहा है…",
    find_matching_btn: "मैचिंग योजनाएं खोजें",
    enter_manually: "गाइडेड फॉर्म के साथ मैन्युअल रूप से विवरण दर्ज करें",
    back_to_natural: "← प्राकृतिक भाषा इनपुट पर वापस जाएं",
    here_is_what_understood: "✨ यहाँ है जो मुझे समझ आया",
    business_project: "व्यापार / परियोजना",
    amount: "राशि",
    annual_income: "वार्षिक आय",
    social_category: "सामाजिक श्रेणी",
    state_prompt: "📍 आप किस राज्य से आवेदन कर रहे हैं? *",
    error_describe_need: "कृपया अपनी वित्तीय आवश्यकता या परियोजना आवश्यकता का वर्णन करें।",
    error_select_state: "आप किस राज्य से आवेदन कर रहे हैं?",
    error_nlu_failed: "क्षमा करें, हम अभी आपकी प्रार्थना को समझ नहीं सके। कृपया पुनः प्रयास करें।",
    error_select_category: "कृपया अपनी सामाजिक श्रेणी चुनें।",
    error_valid_cost: "कृपया एक वैध परियोजना लागत दर्ज करें।",
    error_valid_income: "कृपया एक वैध वार्षिक पारिवारिक आय दर्ज करें।",
    error_valid_state: "कृपया अपना निवासी राज्य दर्ज करें।",
    project_type_label: "परियोजना प्रकार / व्यापार विचार",
    project_cost_label: "आवश्यक राशि (₹) *",
    family_income_label: "वार्षिक पारिवारिक आय (₹) *",
    social_category_label: "सामाजिक श्रेणी *",
    state_label: "निवासी राज्य *",
    rec_evaluated: "मूल्यांकन की गई योजनाएं",
    rec_title: "अनुशंसित योजनाएं",
    rec_sub: "आपके प्रोफाइल के आधार पर शीर्ष सरकारी योजनाएं।",
    finding_best_schemes: "आपके लिए सर्वश्रेष्ठ योजनाएं खोजी जा रही हैं…",
    loading_step_1: "आपकी आवश्यकता को समझा जा रहा है",
    loading_step_2: "प्रासंगिक योजनाओं की खोज",
    loading_step_3: "पात्रता की जांच की जा रही है",
    loading_step_4: "आपके परिणाम तैयार किए जा रहे हैं",
    status_eligible: "पात्र (ELIGIBLE)",
    status_requires_verification: "सत्यापन आवश्यक (REQUIRES VERIFICATION)",
    status_ineligible: "अपात्र (INELIGIBLE)",
    gov_sector: "सरकारी क्षेत्र",
    channel_partner: "चैनल पार्टनर",
    max_benefit: "अधिकतम लाभ",
    match_confidence: "मैच आत्मविश्वास",
    view_details: "योजना विवरण देखें",
    no_matching: "कोई मेल खाने वाली योजना नहीं मिली",
    no_matching_sub: "अपने खोज मानदंडों को समायोजित करने का प्रयास करें।",
    back_to_find: "वापस योजना खोजें पर जाएं",
    back_to_results: "← परिणामों पर वापस जाएं",
    related_schemes: "अन्य प्रासंगिक योजनाएं",
    scheme_details_title: "योजना विवरण",
    eligibility_docs_title: "पात्रता और आवश्यक दस्तावेज",
    documents: "आवश्यक दस्तावेज",
    fin_support_title: "वित्तीय सहायता और लाभ",
    estimate_emi: "EMI का अनुमान लगाएं",
    find_nearby_partner: "चैनल पार्टनर खोजें",
    partners_title: "निकटतम पार्टनर खोजें",
    partners_sub: "इस योजना के लिए निकटतम भौतिक शाखा या सेवा केंद्र खोजें।",
    searching_near: "📍 के पास खोज रहे हैं:",
    use_current_location: "📍 वर्तमान स्थान का उपयोग करें",
    getting_location: "आपका स्थान खोजा जा रहा है...",
    location_denied: "स्थान की अनुमति अस्वीकृत। कृपया नीचे अपना शहर दर्ज करें।",
    enter_location_ph: "शहर या पिनकोड दर्ज करें (जैसे नोएडा, दिल्ली, 110001)",
    search_location: "स्थान खोजें",
    filter_by_institution: "संस्थान के प्रकार के आधार पर फ़िल्टर करें",
    distance_away: "किमी दूर",
    get_directions: "🧭 Mappls पर दिशा-निर्देश खोलें",
    mappls_pin: "Mappls पिन",
    find_other_schemes: "← अन्य योजनाएं खोजें",
    back_home: "मुख्य पृष्ठ पर जाएं",
    footer_motto: "अधिक जागरूकता → बेहतर विकल्प → उज्ज्वल भविष्य",
    footer_copy: "© स्कीम कंपास • सरकारी योजना खोज प्रोटोटाइप",
  },
  kn: {
    brand_title: "ಸ್ಕೀಮ್",
    brand_accent: "ಕಂಪಾಸ್",
    brand_sub: "ಸರಿಯಾದ ಸರ್ಕಾರಿ ಯೋಜನೆಗೆ ನಿಮ್ಮ ಮಾರ್ಗದರ್ಶಿ",
    nav_home: "ಮುಖಪುಟ",
    nav_find_schemes: "ಯೋಜನೆಗಳನ್ನು ಹುಡುಕಿ",
    nav_how_it_works: "ಇದು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ",
    nav_about: "ನಮ್ಮ ಬಗ್ಗೆ",
    nav_help: "ಸಹಾಯ ಮತ್ತು ಬೆಂಬಲ",
    nav_calculator: "ಸಾಲದ ಕ್ಯಾಲ್ಕುಲೇಟರ್",
    nav_partners: "ಚಾನೆಲ್ ಪಾಲುದಾರರು",
    gov_title: "ಭಾರತ ಸರ್ಕಾರ",
    gov_ministry: "ಸಾಮಾಜಿಕ ನ್ಯಾಯ ಮತ್ತು ಸಬಲೀಕರಣ ಸಚಿವಾಲಯ",
    hero_eyebrow: "ಸರ್ಕಾರಿ ಯೋಜನೆ ಅನ್ವೇಷಣೆ ಪೋರ್ಟಲ್",
    hero_title_1: "ನಿಮಗಾಗಿ ಸರಿಯಾದ",
    hero_title_2: "ಸರ್ಕಾರಿ ಯೋಜನೆಯನ್ನು",
    hero_title_3: "ಹುಡುಕಿ",
    hero_desc: "ನಿಮ್ಮ ಅಗತ್ಯಗಳು, ಅರ್ಹತೆಗಳು ಮತ್ತು ಗುರಿಗಳ ಆಧಾರದ ಮೇಲೆ ಹಣಕಾಸು ಮತ್ತು ಶೈಕ್ಷಣಿಕ ಸಹಾಯ ಯೋಜನೆಗಳನ್ನು ಸುಲಭವಾಗಿ ಕಂಡುಕೊಳ್ಳಿ.",
    hero_btn: "ಯೋಜನೆಯನ್ನು ಹುಡುಕಿ",
    need_heading: "ನಿಮಗೆ ಯಾವ ಸಹಾಯ ಬೇಕು?",
    need_sub: "ಒಂದು ಆಯ್ಕೆಯನ್ನು ಆರಿಸಿ ಮತ್ತು ನಾವು ಸೂಕ್ತವಾದ ಸರ್ಕಾರಿ ಯೋಜನೆಗಳ ಮೂಲಕ ನಿಮಗೆ ಮಾರ್ಗದರ್ಶನ ನೀಡುತ್ತೇವೆ.",
    need_biz_title: "ವ್ಯಾಪಾರ ಪ್ರಾರಂಭಿಸಿ",
    need_biz_desc: "ನಿಮ್ಮ ವ್ಯಾಪಾರವನ್ನು ಪ್ರಾರಂಭಿಸಲು ಹಣಕಾಸಿನ ಸಹಾಯವನ್ನು ಅನ್ವೇಷಿಸಿ.",
    need_edu_title: "ಶಿಕ್ಷಣ ಸಹಾಯ",
    need_edu_desc: "ಶಿಕ್ಷಣ ಸಾಲಗಳು ಮತ್ತು ಹಣಕಾಸಿನ ನೆರವು ಕಂಡುಕೊಳ್ಳಿ.",
    need_growth_title: "ವ್ಯಾಪಾರ ವಿಸ್ತರಣೆ",
    need_growth_desc: "ನಿಮ್ಮ ವ್ಯಾಪಾರವನ್ನು ಬೆಳೆಸಲು ಬೆಂಬಲವನ್ನು ಹುಡುಕಿ.",
    need_money_title: "ಇತರ ಹಣಕಾಸು ಅಗತ್ಯಗಳು",
    need_money_desc: "ಇತರ ಹಣಕಾಸಿನ ನೆರವಿನ ಆಯ್ಕೆಗಳನ್ನು ಅನ್ವೇಷಿಸಿ.",
    explore: "ಅನ್ವೇಷಿಸಿ",
    trust_gov_title: "ಸರ್ಕಾರದಿಂದ ನಂಬಿಕಾರ್ಹ",
    trust_gov_desc: "ಅಧಿಕೃತ ಯೋಜನಾ ಮಾಹಿತಿ",
    trust_safe_title: "ಸುರಕ್ಷಿತ ಮತ್ತು ಭದ್ರ",
    trust_safe_desc: "ನಿಮ್ಮ ಮಾಹಿತಿ ಸುರಕ್ಷಿತವಾಗಿದೆ",
    trust_partners_title: "100+ ಚಾನೆಲ್ ಪಾಲುದಾರರು",
    trust_partners_desc: "ಹಣಕಾಸು ಜಾಲದಾದ್ಯಂತ",
    trust_coverage_title: "ಸಂಪೂರ್ಣ ಭಾರತದಾದ್ಯಂತ ಸೇವೆ",
    trust_coverage_desc: "ಭಾರತದಾದ್ಯಂತ ಬೆಂಬಲ",
    step1_eyebrow: "ಹಂತ 1 / 2",
    step1_title: "ನೀವು ಏನನ್ನು ಹುಡುಕುತ್ತಿದ್ದೀರಿ?",
    step1_sub: "ಅರ್ಹ ಸರ್ಕಾರಿ ಯೋಜನೆಗಳನ್ನು ಅನ್ವೇಷಿಸಲು ನಿಮ್ಮ ಅಗತ್ಯವನ್ನು ಆಯ್ಕೆಮಾಡಿ.",
    continue: "ಮುಂದುವರಿಸಿ",
    ai_badge: "ಸ್ಕೀಮ್ ಕಂಪಾಸ್ AI",
    natural_form_title: "ನಿಮಗೆ ಏನು ಬೇಕು ಎಂದು ಹೇಳಿ",
    natural_form_desc: "ನಿಮ್ಮ ಸ್ವಂತ ಮಾತುಗಳಲ್ಲಿ ನಿಮ್ಮ ಅಗತ್ಯವನ್ನು ವಿವರಿಸಿ. ನಮ್ಮ AI ಅದನ್ನು ಅರ್ಥಮಾಡಿಕೊಂಡು ಸೂಕ್ತ ಯೋಜನೆಗಳನ್ನು ಹುಡುಕುತ್ತದೆ.",
    guided_form_title: "ಮಾರ್ಗದರ್ಶಿತ ಅರ್ಜಿ ನಮೂನೆ",
    guided_form_desc: "ಸೂಕ್ತ ಸರ್ಕಾರಿ ಯೋಜನೆಗಳನ್ನು ಅನ್ವೇಷಿಸಲು ನಿಮ್ಮ ವಿವರಗಳನ್ನು ಹಸ್ತಚಾಲಿತವಾಗಿ ಭರ್ತಿ ಮಾಡಿ.",
    natural_input_ph: 'ಉದಾ. "ಕರ್ನಾಟಕದಲ್ಲಿ ಕಿರಾಣಿ ಅಂಗಡಿ ತೆರೆಯಲು ನನಗೆ 2.5 ಲಕ್ಷ ಸಾಲ ಬೇಕು. ವಾರ್ಷಿಕ ಆದಾಯ 1.5 ಲಕ್ಷ."',
    understanding_request: "ನಿಮ್ಮ ಅಗತ್ಯವನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಲಾಗುತ್ತಿದೆ…",
    find_matching_btn: "ಸರಿಯಾಗಿ ಹೊಂದುವ ಯೋಜನೆಗಳನ್ನು ಹುಡುಕಿ",
    enter_manually: "ಮಾರ್ಗದರ್ಶಿತ ನಮೂನೆಯೊಂದಿಗೆ ವಿವರಗಳನ್ನು ಹಸ್ತಚಾಲಿತವಾಗಿ ನಮೂದಿಸಿ",
    back_to_natural: "← ನೈಸರ್ಗಿಕ ಭಾಷಾ ಇನ್‌ಪುಟ್‌ಗೆ ಹಿಂತಿರುಗಿ",
    here_is_what_understood: "✨ ನಾನು ಅರ್ಥಮಾಡಿಕೊಂಡದ್ದು ಇಲ್ಲಿದೆ",
    business_project: "ವ್ಯಾಪಾರ / ಯೋಜನೆ",
    amount: "ಮೊತ್ತ",
    annual_income: "ವಾರ್ಷಿಕ ಆದಾಯ",
    social_category: "ಸಾಮಾಜಿಕ ವರ್ಗ",
    state_prompt: "📍 ನೀವು ಯಾವ ರಾಜ್ಯದಿಂದ ಅರ್ಜಿ ಸಲ್ಲಿಸುತ್ತಿದ್ದೀರಿ? *",
    error_describe_need: "ದಯವಿಟ್ಟು ನಿಮ್ಮ ಹಣಕಾಸಿನ ಅಗತ್ಯ ಅಥವಾ ಯೋಜನೆಯ ಅಗತ್ಯವನ್ನು ವಿವರಿಸಿ.",
    error_select_state: "ನೀವು ಯಾವ ರಾಜ್ಯದಿಂದ ಅರ್ಜಿ ಸಲ್ಲಿಸುತ್ತಿದ್ದೀರಿ?",
    error_nlu_failed: "ಕ್ಷಮಿಸಿ, ಸದ್ಯಕ್ಕೆ ನಿಮ್ಮ ವಿನಂತಿಯನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
    error_select_category: "ದಯವಿಟ್ಟು ನಿಮ್ಮ ಸಾಮಾಜಿಕ ವರ್ಗವನ್ನು ಆಯ್ಕೆಮಾಡಿ.",
    error_valid_cost: "ದಯವಿಟ್ಟು ಮಾನ್ಯವಾದ ಯೋಜನಾ ವೆಚ್ಚವನ್ನು ನಮೂದಿಸಿ.",
    error_valid_income: "ದಯವಿಟ್ಟು ಮಾನ್ಯವಾದ ಕುಟುಂಬದ ಆದಾಯವನ್ನು ನಮೂದಿಸಿ.",
    error_valid_state: "ದಯವಿಟ್ಟು ನಿಮ್ಮ ರಾಜ್ಯವನ್ನು ನಮೂದಿಸಿ.",
    project_type_label: "ಯೋಜನೆಯ ಪ್ರಕಾರ / ವ್ಯಾಪಾರದ ಕಲ್ಪನೆ",
    project_cost_label: "ಅಗತ್ಯವಿರುವ ಮೊತ್ತ (₹) *",
    family_income_label: "ವಾರ್ಷಿಕ ಕೌಟುಂಬಿಕ ಆದಾಯ (₹) *",
    social_category_label: "ಸಾಮಾಜಿಕ ವರ್ಗ *",
    state_label: "ನಿವಾಸಿ ರಾಜ್ಯ *",
    rec_evaluated: "ಮೌಲ್ಯಮಾಪನ ಮಾಡಲಾದ ಯೋಜನೆಗಳು",
    rec_title: "ಶಿಫಾರಸು ಮಾಡಲಾದ ಯೋಜನೆಗಳು",
    rec_sub: "ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಆಧಾರದ ಮೇಲೆ ಅತ್ಯುತ್ತமாக ಮೌಲ್ಯಮಾಪನ ಮಾಡಲಾದ ಯೋಜನೆಗಳು.",
    finding_best_schemes: "ನಿಮಗಾಗಿ ಅತ್ಯುತ್ತಮ ಯೋಜನೆಗಳನ್ನು ಹುಡುಕಲಾಗುತ್ತಿದೆ…",
    loading_step_1: "ನಿಮ್ಮ ಅಗತ್ಯವನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಲಾಗುತ್ತಿದೆ",
    loading_step_2: "ಸಂಬಂಧಿತ ಯೋಜನೆಗಳನ್ನು ಹುಡುಕಲಾಗುತ್ತಿದೆ",
    loading_step_3: "ಅರ್ಹತೆಯನ್ನು ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ",
    loading_step_4: "ನಿಮ್ಮ ಫಲಿತಾಂಶಗಳನ್ನು ಸಿದ್ಧಪಡಿಸಲಾಗುತ್ತಿದೆ",
    status_eligible: "ಅರ್ಹರು (ELIGIBLE)",
    status_requires_verification: "ಪರಿಶೀಲನೆ ಅಗತ್ಯವಿದೆ (REQUIRES VERIFICATION)",
    status_ineligible: "ಅನರ್ಹರು (INELIGIBLE)",
    gov_sector: "ಸರ್ಕಾರಿ ವಲಯ",
    channel_partner: "ಚಾನೆಲ್ ಪಾಲುದಾರ",
    max_benefit: "ಗರಿಷ್ಠ ಪ್ರಯೋಜನ",
    match_confidence: "ಹೊಂದಾಣಿಕೆಯ ವಿಶ್ವಾಸಾರ್ಹತೆ",
    view_details: "ಯೋಜನೆಯ ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಿ",
    no_matching: "ಯಾವುದೇ ಸೂಕ್ತ ಯೋಜನೆಗಳು ಕಂಡುಬಂದಿಲ್ಲ",
    no_matching_sub: "ನಿಮ್ಮ ಹುಡುಕಾಟದ ಮಾನದಂಡಗಳನ್ನು ಬದಲಾಯಿಸಿ ಪ್ರಯತ್ನಿಸಿ.",
    back_to_find: "ಹಿಂತಿರುಗಿ ಯೋಜನೆ ಹುಡುಕಿ",
    back_to_results: "← ಫಲಿತಾಂಶಗಳಿಗೆ ಹಿಂತಿರುಗಿ",
    related_schemes: "ಇತರ ಸೂಕ್ತ ಯೋಜನೆಗಳು",
    scheme_details_title: "ಯೋಜನೆಯ ವಿವರಗಳು",
    eligibility_docs_title: "ಅರ್ಹತೆ ಮತ್ತು ಅಗತ್ಯ ದಾಖಲೆಗಳು",
    documents: "ಅಗತ್ಯ ದಾಖಲೆಗಳು",
    fin_support_title: "ಹಣಕಾಸು ನೆರವು ಮತ್ತು ಪ್ರಯೋಜನಗಳು",
    estimate_emi: "EMI ಅಂದಾಜಿಸಿ",
    find_nearby_partner: "ಚಾನೆಲ್ ಪಾಲುದಾರರನ್ನು ಹುಡುಕಿ",
    partners_title: "ಹತ್ತಿರದ ಪಾಲುದಾರರನ್ನು ಹುಡುಕಿ",
    partners_sub: "ಈ ಯೋಜನೆಗಾಗಿ ಹತ್ತಿರದ ಶಾಖೆ ಅಥವಾ ಸೇವಾ ಕೇಂದ್ರವನ್ನು ಹುಡುಕಿ.",
    searching_near: "📍 ಹತ್ತಿರ ಹುಡುಕಲಾಗುತ್ತಿದೆ:",
    use_current_location: "📍 ಪ್ರಸ್ತುತ ಸ್ಥಳವನ್ನು ಬಳಸಿ",
    getting_location: "ನಿಮ್ಮ ಸ್ಥಳವನ್ನು ಪತ್ತೆಮಾಡಲಾಗುತ್ತಿದೆ...",
    location_denied: "ಸ್ಥಳದ ಅನುಮತಿ ನಿರಾಕರಿಸಲಾಗಿದೆ. ದಯವಿಟ್ಟು ನಿಮ್ಮ ನಗರವನ್ನು ನಮೂದಿಸಿ.",
    enter_location_ph: "ನಗರ ಅಥವಾ ಪಿನ್‌ಕೋಡ್ ನಮೂದಿಸಿ (ಉದಾ. ಬೆಂಗಳೂರು, ಮೈಸೂರು, 560001)",
    search_location: "ಸ್ಥಳವನ್ನು ಹುಡುಕಿ",
    filter_by_institution: "ಸಂಸ್ಥೆಯ ಪ್ರಕಾರದ ಆಧಾರದ ಮೇಲೆ ಫಿಲ್ಟರ್ ಮಾಡಿ",
    distance_away: "ಕಿಮೀ ದೂರದಲ್ಲಿದೆ",
    get_directions: "🧭 Mappls ನಲ್ಲಿ ಮಾರ್ಗಸೂಚಿ ತೆರೆಯಿರಿ",
    mappls_pin: "Mappls ಪಿನ್",
    find_other_schemes: "← ಇತರ ಯೋಜನೆಗಳನ್ನು ಹುಡುಕಿ",
    back_home: "ಮುಖಪುಟಕ್ಕೆ ಹಿಂತಿರುಗಿ",
    footer_motto: "ಹೆಚ್ಚಿನ ಅರಿವು → ಉತ್ತಮ ಆಯ್ಕೆಗಳು → ಉಜ್ವಲ ಭವಿಷ್ಯ",
    footer_copy: "© ಸ್ಕೀಮ್ ಕಂಪಾಸ್ • ಸರ್ಕಾರಿ ಯೋಜನೆ ಅನ್ವೇಷಣೆ ಪ್ರೋಟೋಟೈಪ್",
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState("en");

  useEffect(() => {
    const saved = localStorage.getItem("sc_language");
    if (saved && ["en", "ta", "hi", "kn"].includes(saved)) {
      setLang(saved);
    }
  }, []);

  const changeLanguage = (newLang) => {
    if (["en", "ta", "hi", "kn"].includes(newLang)) {
      setLang(newLang);
      localStorage.setItem("sc_language", newLang);
    }
  };

  const t = (key) => {
    return translations[lang]?.[key] || translations.en?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    return {
      lang: "en",
      changeLanguage: () => {},
      t: (key) => key,
    };
  }
  return context;
}
